# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
xcode_workspace: Example/JSSideSlipMenu.xcworkspace
xcode_scheme: JSSideSlipMenu-Example
podfile: Example/Podfile
cache: cocoapods
befor_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild clean build test -enableCodeCoverage YES -workspace Example/JSSideSlipMenu.xcworkspace -scheme JSSideSlipMenu-Example -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
